Add Hexagon arch and mach
BinaryAnalysisPlatform/bap-frames pull request #23
Opened 2023-03-17 18:58 UTC by Rot127

Adds the Hexagon architecture enum entry and defines for machine types.

2023-07-05 04:23 UTC, XVilka requested changes
@Rot127 you need to update also the `lib/frame_arch.ml`

2023-07-05 09:16 UTC, Rot127 commented
Ah right, will take care of it in August.

2023-09-06 04:00 UTC, XVilka approved these changes

2023-09-06 10:26 UTC, thestr4ng3r requested changes

2023-09-06 10:26 UTC, thestr4ng3r commented on libtrace/src/frame_arch.h
> +  frame_arch_hexagon, /* Qualcomm DSP architecture Hexagon */
Please put this after the `frame_arch_sm83` (as well as in `frame_arch.ml`) so compatibility with previous commits on master is preserved.

2023-09-07 04:34 UTC, thestr4ng3r approved these changes

2023-09-07 04:38 UTC, XVilka approved these changes

2023-09-22 16:21 UTC, ivg approved these changes
👍🏻

2023-09-22 16:26 UTC, merged